// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARd6S7abCg1gOY3M_obaTiy9ocLGqZZVA',
    appId: '1:197506711883:web:2621f66291dc2d12c128ce',
    messagingSenderId: '197506711883',
    projectId: 'buoi14-eb12f',
    authDomain: 'buoi14-eb12f.firebaseapp.com',
    storageBucket: 'buoi14-eb12f.firebasestorage.app',
    measurementId: 'G-MF7D1CM7DX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDT79p5PSTcKQ4xHGQHTbGYwJSY-q9fsKM',
    appId: '1:197506711883:android:f67266ade0c2e109c128ce',
    messagingSenderId: '197506711883',
    projectId: 'buoi14-eb12f',
    storageBucket: 'buoi14-eb12f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAsLaSFG5vItq4-W_mZbKbDVe3pdmFg3MY',
    appId: '1:197506711883:ios:84611b51c279aafbc128ce',
    messagingSenderId: '197506711883',
    projectId: 'buoi14-eb12f',
    storageBucket: 'buoi14-eb12f.firebasestorage.app',
    iosBundleId: 'com.example.chude14',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAsLaSFG5vItq4-W_mZbKbDVe3pdmFg3MY',
    appId: '1:197506711883:ios:84611b51c279aafbc128ce',
    messagingSenderId: '197506711883',
    projectId: 'buoi14-eb12f',
    storageBucket: 'buoi14-eb12f.firebasestorage.app',
    iosBundleId: 'com.example.chude14',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyARd6S7abCg1gOY3M_obaTiy9ocLGqZZVA',
    appId: '1:197506711883:web:e472259f1dce55dcc128ce',
    messagingSenderId: '197506711883',
    projectId: 'buoi14-eb12f',
    authDomain: 'buoi14-eb12f.firebaseapp.com',
    storageBucket: 'buoi14-eb12f.firebasestorage.app',
    measurementId: 'G-WSECQXZV4S',
  );
}
